extends: base.j2
default_block: blog

language: fr
lc: fr_FR

l10n:
  created_by: "Créé par"
  posted: "Posté le"
  tags: "Catégorie"
  readmore: "Lire la suite"
  translations: "Aussi disponible en"
